Repository ArkEcosystem/python-crypto, pull requests merged in 2019-05, with the labels that each got.

#79 chore: update contribution link
  .github/CONTRIBUTING.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#80 feat: support new vendorfield length
  crypto/transactions/transaction.py
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Feature

#82 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task

#83 chore: add itsanametoo to code owners
  CODEOWNERS
Labels: Complexity: Low, Type: Task
