Repository ArkEcosystem/python-crypto, pull requests merged in 2020-02, with the labels that each got.

#106 fix: update second_sign method to use schnorr
  crypto/transactions/builder/base.py
  crypto/transactions/serializer.py
  crypto/transactions/transaction.py
  tests/transactions/builder/test_transfer.py
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved

#111 release: 1.0.0
  CHANGELOG.md
  setup.py
Labels: Complexity: Low, Type: Release

#112 chore: fix wrong release year
  CHANGELOG.md
Labels: Complexity: Low, Type: Task
